language: node_js
node_js:
  - "6.11.1"
services:
  - "postgresql"
addons:
  postgresql: "9.6"
env:
  - PG_CONNECTION_STRING_TEST="postgres://postgres@localhost:5432/phonebank_test"
  - TWILIO_ACCOUNT_SID="AC99999999999999999999999999999999"
  - TWILIO_AUTH_TOKEN="a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9"
  - TWILIO_CALLER_ID=""+15555555555"
before_script:
  - psql -c 'create database phonebank_test;' -U postgres
cache:
  directories:
    - node_modules
